config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :developers, path: 'developers', controllers: {
    sessions: 'developers/sessions',
    passwords: 'developers/passwords',
    registrations: 'developers/registrations',
    confirmations: 'developers/confirmations'
  }

  root 'pages#home'

  # Posts routes
  resources :posts, only: %i[index], path: 'feed' do
    # Likes that belongs to posts
    member do
      put 'like', to: 'posts#like'
      get 'media', to: 'posts#media_open'
    end

    # Comments that belongs to posts
    resources :comments, only: %i[create destroy] do
      # Likes that belongs to comments
      member do
        put 'like', to: 'comments#like'
      end
    end
  end

  # Bots routes
  resources :bots, only: %i[follow show create new update] do
    member do
      put :follow, to: 'bots#follow'
      put :regenerate_keys
    end

    # Posts belongs to bots
    resources :posts, only: %i[show destroy]
  end

  resources :bots, only: %i[destroy], path: '/:id'
  resources :bots, only: %i[edit udpdate]
  patch 'bots/:username/edit', to: 'bots#update'

  get 'report', to: 'pages#report'

  resources :developers, only: %i[show]

  resource :autocomplete, only: %i[show]

  get 'rules', to: 'pages#rules'
  get 'search', to: 'searches#search'
end

app/models/developer.rb
# frozen_string_literal: true

# Developer model
class Developer < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :validatable, :timeoutable,
         authentication_keys: [:login]

  extend FriendlyId
  friendly_id :username, use: :slugged # username as friendly_id

  include AvatarUploader::Attachment(:avatar)
  include CoverUploader::Attachment(:cover)

  attr_writer :login

  extend UsernamesBlocklist
  validates :friendly_id, exclusion: { in: blocklist }

  validate :validate_username, if: :username_changed?

  # regex to assure username doesn't have a @
  validates_format_of :username, with: /\A[a-zA-Z0-9_-]*\z/
  validates_length_of :username, minimum: 4, maximum: 32
  before_save :downcase_username

  # validates name to ensure it doesn't contain numbers nor symbols
  validates :name, format: { with: /\A[^0-9`!@#$%^&*+_=]+\z/ }
  validates_length_of :name, minimum: 4, maximum: 64

  # validate password strength
  validates :password, password_strength: { min_entropy: 15, use_dictionary: true, min_word_length: 6 },
                       if: :encrypted_password_changed?

  has_many :bots
  has_many :likes, as: :liker
  has_many :comments, as: :commenter

  # validates length of developer's bio
  validates_length_of :bio, maximum: 512

  acts_as_follower

  # Save browser's locale as default user's preference locale
  before_create do |dev|
    dev.locale = I18n.locale
  end

  # remove all capitals from usernames
  def downcase_username
    username.downcase!
  end

  def login
    @login or username or email
  end

  # Update user's friendly_id when username is changed
  def should_generate_new_friendly_id?
    username_changed?
  end

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    # set all bots as orphans
    bots.find_each do |bot|
      bot.update_attribute(:is_orphan, true)
    end
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  # override auth method to allow login with different params
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value ',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  # validates if username is not taken
  def validate_username
    if Developer.where(email: username.downcase).exists?
      errors.add(:username, :already_taken)
    elsif Developer.where(username: username.downcase).exists?
      errors.add(:username, :already_taken)
    elsif Bot.where(username: username.downcase).exists?
      errors.add(:username, :already_taken)
    end
  end

  # send emails in background
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/developers/confirmations_controller.rb
# frozen_string_literal: true

class Developers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/developers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Developers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/developers/passwords_controller.rb
# frozen_string_literal: true

class Developers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/developers/registrations_controller.rb
# frozen_string_literal: true

module Developers
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: %i[create]
    before_action :configure_account_update_params, only: %i[update]
    after_action :save_user_timezone, only: :create

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    def destroy
      resource.soft_delete
      Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
      set_flash_message :notice, :destroyed
      yield resource if block_given?
      respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
    end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    private

    # Save user's timezone on sign-up
    def save_user_timezone
      return unless resource.persisted?

      resource.update(timezone: cookies[:timezone])
    end

    protected

    # Permit avatar and cover for sign_up
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up,
                                        keys: %i[name username email password password_confirmation remember_me avatar
                                                 cover])
    end

    # Permit avatar cover for update
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update,
                                        keys: %i[name username email password password_confirmation avatar
                                                 cover bio locale timezone])
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/developers/sessions_controller.rb
# frozen_string_literal: true

class Developers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/developers/unlocks_controller.rb
# frozen_string_literal: true

class Developers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/developers_controller.rb
# frozen_string_literal: true

# Developers general Controller
class DevelopersController < ApplicationController
  before_action :find_dev, only: %i[show]

  def show
    @bots = Bot.where(developer_id: @developer.id).order('created_at ASC')
    @posts = []
    @bots.each do |b|
      p = Post.where(bot_id: b.id).last
      @posts.push(p) unless p.nil?
    end
  end

  private

  def find_dev
    @developer = Developer.friendly.find(params[:id])
  end
end

app/helpers/developers_helper.rb
# frozen_string_literal: true

# Helpers for Developers
module DevelopersHelper
  def created_at_formatted(created_at)
    I18n.l(created_at.in_time_zone, format: :date)
  end
end

app/views/developers/_developer.html.erb
<%= stylesheet_link_tag 'profiles' %>
<div class="row m-0">
  <div class="resource-container container">
    <div class="resource-cardbox shadow-lg bg-white">
      <div class="resource-cardbox-heading rounded">
        <div class="resource-media m-0">
          <div class="d-flex mr-3">
            <%= image_tag (developer.avatar_url(:small) || developer.avatar_url || 'default.png'), class: 'avatar img-fluid' %>
          </div>
          <div class="resource-media-body">
            <div class="m-0 d-flex justify-content-between">
              <div>
                <%= link_to developer.name, developer_path(developer)%>
                <% if developer.verified %>
                  <i id="verified-icon" class="fas fa-check-circle" style="color:#1a8cff"></i>
                <% end %>
                •
                <small><span><i class="icon ion-md-pin"></i> <%= '@' + developer.username %></span></small>
              </div>
            </div>
            <small><span><i class="icon ion-md-time"></i><%= I18n.t('developers.show.joined') %><%= created_at_formatted(developer.created_at) %></span></small>
            <p class="card-text limit-text">
              <%= developer.bio %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/developers/show.html.erb
<%= stylesheet_link_tag 'profiles' %>

<div class="col d-flex justify-content-center page">
  <div id="profile-card" class="card w-100">
    <div>
      <%= image_tag (@developer.cover_url(:cover) || @developer.cover_url || 'default_cover.png'), class: 'card-img-top resource-cover-responsive', id: 'profile-card-img-top' %>
    </div>
    <div class="card-body">
      <%= image_tag (@developer.avatar_url(:medium) || @developer.avatar_url || 'default.png'), class: 'rounded-circle profile-image' %>
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <h4 class="card-title"><%= @developer.name %>
            <% if @developer.verified %>
              <i id="verified-icon" class="fas fa-check-circle" style="color:#1a8cff"></i>
            <% end %>
          </h4>
          <p class="mt-n3">@<%= @developer.username %></p>
        </div>

        <div>
          <% if current_developer && @developer == current_developer %>
            <%= link_to edit_developer_registration_path, class: 'no-underline pt-0 pb-0' do%>
              <i class="fas fa-user-edit"></i>
             <% end %>
          <% end %>
        </div>
      </div>
        <p class="card-text">
          <%= @developer.bio %>
        </p>
      <p class="card-text">
        <small class="text-muted"><%= I18n.t('developers.show.joined') %>
          <%= created_at_formatted(@developer.created_at) %></small>
      </p>
    </div>
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-latest-tab" data-toggle="tab" href="#nav-latest" role="tab" aria-controls="nav-latest" aria-selected="true"> <%= I18n.t('developers.show.tabs.latest') %></a>
        <a class="nav-item nav-link" id="nav-bots-tab" data-toggle="tab" href="#nav-bots" role="tab" aria-controls="nav-bots" aria-selected="false"><%= I18n.t('developers.show.tabs.bots') %></a>
      </div>
    </nav>
  </div>
</div>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active p-2" id="nav-latest" role="tabpanel" aria-labelledby="nav-latest-tab">
    <div>
      <%= render @posts %>
    </div>
  </div>
  <div class="tab-pane fade p-2" id="nav-bots" role="tabpanel" aria-labelledby="nav-bots-tab">
    <% if current_developer == @developer && current_developer.bots.count < 5 %>
      <div class="d-flex justify-content-center">
        <%= link_to new_bot_path, class: 'no-underline btn-new' do %>
          <%=I18n.t('developers.show.buttons.new-bot')%>
          <i class="fas fa-plus"></i>
        <% end %>
      </div>
    <% end %>
    <div id="bots" class="container">
      <%= render @bots %>
    </div>
  </div>
</div>