config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :developers, path: 'developers', controllers: {
    sessions: 'developers/sessions',
    passwords: 'developers/passwords',
    registrations: 'developers/registrations',
    confirmations: 'developers/confirmations'
  }

  root 'pages#home'

  # Posts routes
  resources :posts, only: %i[index], path: 'feed' do
    # Likes that belongs to posts
    member do
      put 'like', to: 'posts#like'
      get 'media', to: 'posts#media_open'
    end

    # Comments that belongs to posts
    resources :comments, only: %i[create destroy] do
      # Likes that belongs to comments
      member do
        put 'like', to: 'comments#like'
      end
    end
  end

  # Bots routes
  resources :bots, only: %i[follow show create new update] do
    member do
      put :follow, to: 'bots#follow'
      put :regenerate_keys
    end

    # Posts belongs to bots
    resources :posts, only: %i[show destroy]
  end

  resources :bots, only: %i[destroy], path: '/:id'
  resources :bots, only: %i[edit udpdate]
  patch 'bots/:username/edit', to: 'bots#update'

  get 'report', to: 'pages#report'

  resources :developers, only: %i[show]

  resource :autocomplete, only: %i[show]

  get 'rules', to: 'pages#rules'
  get 'search', to: 'searches#search'
end

app/models/comment.rb
# frozen_string_literal: true

# Comment model
class Comment < ApplicationRecord
  belongs_to :commenter, polymorphic: true
  belongs_to :commentable, polymorphic: true

  has_many :likes, as: :likeable, dependent: :destroy

  self.per_page = 5

  validates_presence_of :body
  validates_length_of :body, maximum: 512, minimum: 1
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# CommentsController
class CommentsController < ApplicationController
  before_action :authenticate!
  before_action :find_commentable, only: :create
  before_action :find_comment, only: %i[destroy like]
  respond_to :html, :js, :json

  # Create comment for current_developer
  def create
    @commentable.comments.create(commenter_id: current_developer.id, commenter_type: 'Developer',
                                 body: params[:comment][:body])
    redirect_back fallback_location: root_path
  end

  def like
    if !already_liked?
      @comment.likes.create(liker_id: current_developer.id, liker_type: 'Developer')
    else
      @comment.likes.where(liker_id: current_developer.id, liker_type: 'Developer').first.destroy
    end
  end

  # Delete comment
  def destroy
    @comment.destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :post_id, :body)
  end

  # Find commentable with commentable id
  def find_commentable
    @commentable = Post.find(params[:post_id]) if params[:post_id]
  end

  # Find comment with comment.id
  def find_comment
    @comment = Comment.find(params[:id])
  end

  def already_liked?
    @comment.likes.where(liker_id: current_developer.id, liker_type: 'Developer').exists?
  end

  def authenticate!
    return if current_developer
    if action_name == 'like'
      @icon = 'fas fa-heart'
    else
      @icon = 'fas fa-sign-in-alt'
    end

    @action = I18n.t("application.alert." + "comment-" + action_name)
    respond_to do |format|
      format.html {redirect_back fallback_location: root_path}
      format.js {render partial: 'layouts/modals/sign'}
    end
  end
end

app/views/comments/_comment.html.erb
<div class="row m-0">
  <div class="resource-container container">
    <div class="resource-cardbox comment-cardbox mx-2 mb-0 bg-white">
      <div class="resource-cardbox-heading rounded">
        <div class="resource-media m-0">
          <div class="d-flex mr-3">
            <%= image_tag (comment.commenter.avatar_url(:small) || comment.commenter.avatar_url || 'default.png'), class: 'avatar img-fluid' %>
          </div>
          <div class="media-body">
            <p class="m-0">
              <%= link_to comment.commenter.name, comment.commenter.class.name == 'Bot' ? bot_path(comment.commenter) : developer_path(comment.commenter) %>
              <% if comment.commenter.verified %>
                <i id="verified-icon" class="fas fa-check-circle" style="color:#1a8cff"></i>
              <% end %>
              •
              <small><span><i class="icon ion-md-pin"></i> <%= '@' + comment.commenter.username %></span></small>
            </p>
            <small><span><i class="icon ion-md-time"></i> <%= time_ago(comment.created_at) %></span></small>
          </div>
        </div>
      </div>
      <div class="resource-media-text scrollable-paragraph">
       <%= auto_link(comment.body.gsub(/^$\n\n/, ''), link: :urls, html: {target: :_blank}) %>
      </div>
      <div class="resource-cardbox-base">
        <ul>
          <li><a>
            <%= link_to like_post_comment_path(comment.commentable, comment), method: :put, class: 'no-underline', remote: :true do %>
              <% if current_developer && liked(comment.likes) %>
                <i id="comment-like-btn-<%= comment.id %>" class="fas fa-heart" style="color: #9E788F"></i>
              <% else %>
                <i id="comment-like-btn-<%= comment.id %>" class="far fa-heart" style="color: #9E788F"></i>
              <% end %>
            <% end %>
            <span id="comment-likes-count-<%= comment.id %>"><b><%= comment.likes.count %></b></span>
          </a></li>
        </ul>
        <ul class="float-right">
          <li><a>
            <% if current_developer && comment.commenter.id == current_developer.id && comment.commenter.class.name == 'Developer' %>
              <%= link_to post_comment_path(comment.commentable, comment), method: :delete, data: { confirm: I18n.t('application.confirm.are-you-sure'), commit: I18n.t('application.confirm.commit'), cancel: I18n.t('application.confirm.cancel'), icon: "far fa-trash-alt" }, class: 'no-underline' do %>
                <i class="far fa-trash-alt" style="color:red"></i>
              <% end %>
            <% end %>
          </a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/comments/like.js.erb
<% if current_developer && liked(@comment.likes) %>
  $('#comment-like-btn-<%= @comment.id %>').html('<i id="like-btn" class="fas fa-heart" style="color: #9E788F"></i>')
<% else %>
  $('#comment-like-btn-<%= @comment.id %>').html('<i id="like-btn" class="far fa-heart" style="color: #9E788F"></i>')
<% end %>

$('#comment-likes-count-<%= @comment.id %>').html('<b><%= @comment.likes.count %></br>')