config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :developers, path: 'developers', controllers: {
    sessions: 'developers/sessions',
    passwords: 'developers/passwords',
    registrations: 'developers/registrations',
    confirmations: 'developers/confirmations'
  }

  root 'pages#home'

  # Posts routes
  resources :posts, only: %i[index], path: 'feed' do
    # Likes that belongs to posts
    member do
      put 'like', to: 'posts#like'
      get 'media', to: 'posts#media_open'
    end

    # Comments that belongs to posts
    resources :comments, only: %i[create destroy] do
      # Likes that belongs to comments
      member do
        put 'like', to: 'comments#like'
      end
    end
  end

  # Bots routes
  resources :bots, only: %i[follow show create new update] do
    member do
      put :follow, to: 'bots#follow'
      put :regenerate_keys
    end

    # Posts belongs to bots
    resources :posts, only: %i[show destroy]
  end

  resources :bots, only: %i[destroy], path: '/:id'
  resources :bots, only: %i[edit udpdate]
  patch 'bots/:username/edit', to: 'bots#update'

  get 'report', to: 'pages#report'

  resources :developers, only: %i[show]

  resource :autocomplete, only: %i[show]

  get 'rules', to: 'pages#rules'
  get 'search', to: 'searches#search'
end

app/models/post.rb
# frozen_string_literal: true

# Post model
class Post < ApplicationRecord
  belongs_to :bot

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  # using AvatarUploader just to get media_url
  include MediaUploader::Attachment(:media)

  self.per_page = 15
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate!, only: %i[index destroy like]
  before_action :set_post, only: %i[show destroy like media_open]
  respond_to :html, :js, :json

  def index
    @posts = Post.joins("JOIN Follows f ON posts.bot_id = f.followable_id
                          WHERE f.follower_type ~* 'developer'
                          AND (CURRENT_TIMESTAMP - posts.created_at) < INTERVAL '7 days'
                          AND f.follower_id = #{current_developer.id}")
                 .paginate(page: params[:page]).order('created_at DESC')
  end

  def show
    @comments = @post.comments.paginate(page: params[:page]).order('created_at DESC')
  end

  def like
    if !already_liked?
      @post.likes.create(liker_id: current_developer.id, liker_type: 'Developer')
    else
      @post.likes.where(liker_id: current_developer.id, liker_type: 'Developer').first.destroy
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def media_open
    respond_to do |format|
      format.html { redirect_to(@post.media_url(:desktop) || @post.media_url) }
      format.js {}
    end
  end

  private

  def authenticate!
    return if current_developer

    @icon = if action_name == 'like'
              'fas fa-heart'
            else
              'fas fa-sign-in-alt'
            end

    @action = I18n.t("application.alert.post-#{action_name}")
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js { render partial: 'layouts/modals/sign' }
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def already_liked?
    @post.likes.where(liker_id: current_developer.id, liker_type: 'Developer').exists?
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# Posts helpers
module PostsHelper
  # Returns true if current_developer like is found in a posts likes list
  def liked(likes)
    likes.find { |like| like.liker_id == current_developer.id && like.liker_type == 'Developer' }
  end

  def time_ago(created_at)
    difference = Time.now.in_time_zone - created_at.in_time_zone
    if difference < 1.minute
      I18n.t('time.distance.x_seconds_ago', count: (difference / 1.second).to_i)
    elsif difference < 1.hour
      I18n.t('time.distance.x_minutes_ago', count: (difference / 1.minute).to_i)
    elsif difference < 1.day
      I18n.t('time.distance.x_hours_ago', count: (difference / 1.hour).to_i)
    else
      I18n.l(created_at.in_time_zone, format: :date)
    end
  end
end

app/views/posts/_post.html.erb
<%= stylesheet_link_tag 'posts' %>

<div class="row m-0">
  <div class="resource-container container">
    <div class="resource-cardbox shadow-lg bg-white">
      <div class="resource-cardbox-heading rounded">
        <div class="resource-media m-0">
          <div class="d-flex">
            <%= image_tag (post.bot.avatar_url(:small) || post.bot.avatar_url || 'default.png'), class: 'avatar img-fluid' %>
          </div>
          <div class="resource-media-body ml-3">
            <p class="m-0">
              <%= link_to post.bot.name, bot_path(post.bot) %>
              <% if post.bot.verified %>
                <i id="verified-icon" class="fas fa-check-circle" style="color:#1a8cff"></i>
              <% end %>
              •
              <small><span><i class="icon ion-md-pin"></i> <%= '@' + post.bot.username %></span></small>
            </p>
            <small><span><i class="icon ion-md-time"></i> <%= time_ago(post.created_at) %></span></small>
          </div>
        </div>
      </div>
      <div class="resource-media-text scrollable-paragraph">
        <%= auto_link(post.body.gsub(/^$\n\n/, ''), link: :urls, html: {target: :_blank}) %>
      </div>
      <div class="resource-media-item">
        <% if post.media_url %>
          <% if post.media.mime_type == 'video/mp4' %>
          <div class = "video-thumbnail" style="background: url(<%=post.media_url(:thumbnail)%>)">
            <div class = "blurred-thumbnail">
              <%= video_tag (post.media_url(:desktop) || post.media_url), poster: (post.media_url(:thumbnail)), draggable: 'false', class: 'resource-media-responsive resource-video-responsive', controls: true %>
            </div>
          </div>
          <% else %>
            <%= link_to media_post_path(post), method: :get, remote: :true do %>
              <% image_tag (post.media_url(:desktop) || post.media_url), draggable: 'false', class: 'resource-media-responsive' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="resource-cardbox-base">
        <ul>
          <% if request.path != bot_post_path(post.bot, post) %>
            <li><a>
              <%= link_to bot_post_path(post.bot, post), class: 'no-underline' do %>
                <i class="fas fa-comment-alt" style="color:#7CDEDC"></i>
              <% end %>
              <span><b><%= post.comments.count %></b></span>
            </a></li>
          <% end %>
          <li><a>
            <%= link_to like_post_path(post), method: :put, class: 'no-underline', remote: :true do %>
              <% if current_developer && liked(post.likes) %>
                <i id="post-like-btn-<%= post.id %>" class="fas fa-heart" style="color: #9E788F"></i>
              <% else %>
                <i id="post-like-btn-<%= post.id %>" class="far fa-heart" style="color: #9E788F"></i>
              <% end %>
            <% end %>
            <span id="post-likes-count-<%= post.id %>"><b><%= post.likes.count %></b></span>
          </a></li>
        </ul>
        <ul class="float-right">
          <li><a>
            <% if current_developer && post.bot.developer_id == current_developer.id %>
              <%= link_to bot_post_path(post.bot, post), method: :delete, data: { confirm: I18n.t('application.confirm.are-you-sure'), commit: I18n.t('application.confirm.commit'), cancel: I18n.t('application.confirm.cancel'), icon: "far fa-trash-alt"}, class: 'no-underline' do %>
                <i class="far fa-trash-alt" style="color:red"></i>
              <% end %>
            <% end %>
          </a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div id="posts" class="page container">
  <%= render @posts %>
</div>

<div>
  <%= will_paginate @posts %>
</div>

<div class="row m-0">
  <div class="resource-container container">
    <div class="resource-cardbox shadow-lg bg-white">
      <div class="d-flex flex-column align-items-center">
        <i class="fa fa-calendar-check fa-5x m-2" style="color:green"></i>
      </div>
    </div>
  </div>
</div>

app/views/posts/like.js.erb
<% if current_developer && liked(@post.likes) %>
  $('#post-like-btn-<%= @post.id %>').html('<i class="fas fa-heart" style="color: #9E788F"></i>')
<% else %>
  $('#post-like-btn-<%= @post.id %>').html('<i id="like-btn" class="far fa-heart" style="color: #9E788F"></i>')
<% end %>

$('#post-likes-count-<%= @post.id %>').html('<b><%= @post.likes.count %></br>')

app/views/posts/media_open.js.erb
Swal.fire({
  html: '<img src="<%= @post.media_url(:desktop) || @post.media_url %>" style="height: auto; max-height: 100%; width: auto; max-width: 100%">',
  showCloseButton: true,
  focusCancel: false,
  showConfirmButton: false,
  width: 'auto',
  heightAuto: false  
})

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'posts' %>

<div class="page container">
  <%= render @post %>
  <div id="comments" class="comment-section">
    <div class="resource-container container">
      <div class="resource-cardbox">
        <div class="resource-media m-0">
          <%= form_with(model: [@post, @post.comments.build], class:'m-2 w-100 comment-form') do |f| %>
            <%= f.text_area :body, class: 'comment-textbox md-textarea form-control bg-transparent scrollable-paragraph', rows: '3', id: 'comment-textbox', placeholder: '>_' %>
            <%= button_tag type: 'submit', class: "btn btn-comment btn-block", id: "register-button" do %>
                <span><%= I18n.t('posts.show.comment') %></span>
              <i class="fas fa-plus"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <%= render @comments %>
  </div>
</div>
<div class="d-flex justify-content-center">
  <%= will_paginate @comments%>
</div>

app/views/posts/show.js.erb
$('#comments').append('<%= j render @comments %>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @comments %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>