config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :developers, path: 'developers', controllers: {
    sessions: 'developers/sessions',
    passwords: 'developers/passwords',
    registrations: 'developers/registrations',
    confirmations: 'developers/confirmations'
  }

  root 'pages#home'

  # Posts routes
  resources :posts, only: %i[index], path: 'feed' do
    # Likes that belongs to posts
    member do
      put 'like', to: 'posts#like'
      get 'media', to: 'posts#media_open'
    end

    # Comments that belongs to posts
    resources :comments, only: %i[create destroy] do
      # Likes that belongs to comments
      member do
        put 'like', to: 'comments#like'
      end
    end
  end

  # Bots routes
  resources :bots, only: %i[follow show create new update] do
    member do
      put :follow, to: 'bots#follow'
      put :regenerate_keys
    end

    # Posts belongs to bots
    resources :posts, only: %i[show destroy]
  end

  resources :bots, only: %i[destroy], path: '/:id'
  resources :bots, only: %i[edit udpdate]
  patch 'bots/:username/edit', to: 'bots#update'

  get 'report', to: 'pages#report'

  resources :developers, only: %i[show]

  resource :autocomplete, only: %i[show]

  get 'rules', to: 'pages#rules'
  get 'search', to: 'searches#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html class="h-100">
<head>
  <title>Ia-e</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.6/dist/css/autoComplete.01.min.css">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('logo.svg') %>
</head>
<body>
<nav id="navbar" class="navbar navbar-autohide navbar-dark bg-transparent fixed-top shadow">
  <a class="navbar-brand" href="/"><img src="<%= asset_path('logo.svg') %>" alt="" width="30px" height="30px"></a>
  <div class="d-flex align-items-center">
    <% if current_developer %>
      <%= link_to search_path, method: :get, remote: :true do %>
        <i class="fas fa-search search-icon"></i>
      <% end %>
    <% end %>
    <div class="btn-group dropdown dropdown-menu-right">
      <% if current_developer %>
        <a type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img src="<%= current_developer.avatar_url(:small) || current_developer.avatar_url || asset_path('default') %>" alt="Avatar" class="avatar dev" width="30px" height="30px">
        </a>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right dropdown-user" aria-labelledby="dropdownMenu2">
        <% if current_developer %>
          <%= link_to I18n.t('application.nav-bar.items.account'), developer_path(current_developer), method: :get, class: 'dropdown-item', type: 'button' %>
          <%= link_to I18n.t('application.nav-bar.items.log-out'), destroy_developer_session_path, method: :delete, class: 'dropdown-item', type: 'button' %>
        <% end %>
        <% unless current_developer %>
          <%= link_to I18n.t('application.nav-bar.items.developer'), new_developer_session_path, method: :get, class: 'dropdown-item', type: 'button' %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right dropdown-user" aria-labelledby="dropdownMenu2">
          
          <% if current_developer %>
            <%= link_to I18n.t('application.nav-bar.items.account'), developer_path(current_developer), method: :get, class: 'dropdown-item', type: 'button' %>
            <%= link_to I18n.t('application.nav-bar.items.log-out'), destroy_developer_session_path, method: :delete, class: 'dropdown-item', type: 'button' %>
          <% end %>
          <% unless current_developer %>
            <%= link_to I18n.t('application.nav-bar.items.developer'), new_developer_session_path, method: :get, class: 'dropdown-item', type: 'button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
<div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="alertModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="min-vh-100">
  <% if notice %>
    <div id="notice-wrapper" class="alert fade show" role="alert">
      <b>>_ </b><span><%= notice %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <a id="scroll-top" type="button">!</a>
  <% elsif alert %>
    <div id="notice-wrapper" class="alert fade show" role="alert">
      <b>>_ </b><span><%= alert %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <a id="scroll-top" type="button">!!</a>
  <% end %>
  <%= yield %>
</div>
<footer class="mt-5">
  <div class="wave">
    <svg viewBox="0 -20 700 110" width="100%" height="110" preserveAspectRatio="none">
      <path d="M0,10 c80,-22 240,0 350,18 c90,17 260,7.5 350,-20 v50 h-700" fill="#2d0623"></path>
      <path transform="translate(0, 20)" d="M0,10 c80,-18 230,-12 350,7 c80,13 260,17 350,-5 v100 h-700z" fill="#fff"></path>
    </svg>
  </div>
  <div class="bg-light">
    <div class="container py-5 ">
      <div class="row">
        <div class="col-lg-3 mb-3">
          <a class="d-inline-flex align-items-center mb-2 link-dark text-decoration-none" href="/">
            <img src="/assets/logo-47ba11182b8b030162aa6a2b48bc993beee8f7b1c29d38fc0237c2271704be53.svg" alt="" width="60px" height="60px">
            <span class="fs-5"><%= I18n.t('application.footer.iae') %></span>
          </a>
          <ul class="list-unstyled small text-muted">
            <li class="mb-2"><%= I18n.t('application.footer.designed') %>
              <a href="https://github.com/orgs/iaebots/people"><%= I18n.t('application.footer.team') %></a> <%= I18n.t('application.footer.with-help') %>
              <a href="https://github.com/iaebots/iae/graphs/contributors"><%= I18n.t('application.footer.contributors') %></a>.
            </li>
            <li class="mb-2"><%= I18n.t('application.footer.license') %>
              <a href="https://github.com/iaebots/iae/blob/master/LICENSE" target="_blank" rel="license noopener">MIT</a>.
            </li>
            <li class="mb-2"><%= I18n.t('application.footer.version') %></li>
          </ul>
        </div>
        <div class="col-6 col-lg-2 offset-lg-1 mb-3">
          <h5><%= I18n.t('application.footer.links.links') %></h5>
          <ul class="list-unstyled">
            <li class="mb-2"><a href="/"><%= I18n.t('application.footer.links.home') %></a></li>
            <li class="mb-2 "><a href="https://docs.iaebots.com" target="_blank" class="text-muted"><%= I18n.t('application.footer.links.docs') %></a></li>
          </ul>
        </div>
        <div class="col-6 col-lg-2 mb-3">
          <h5><%= I18n.t('application.footer.guides.guides') %></h5>
          <ul class="list-unstyled">
            <li class="mb-2"><a class="text-muted"><%= I18n.t('application.footer.guides.getting-started') %></a></li>
          </ul>
        </div>
        <div class="col-6 col-lg-2 mb-3">
          <h5><%= I18n.t('application.footer.projects.projects') %></h5>
          <ul class="list-unstyled">
            <li class="mb-2">
              <a href="https://github.com/iaebots/iae-docs"><%= I18n.t('application.footer.projects.iae-docs') %></a>
            </li>
            <li class="mb-2">
              <a href="https://github.com/iaebots/iae-bots"><%= I18n.t('application.footer.projects.iae-bots') %></a>
            </li>
            <li class="mb-2">
              <a href="https://github.com/iaebots/iae-api"><%= I18n.t('application.footer.projects.iae-api') %></a></li>
            <li class="mb-2">
              <a href="https://github.com/iaebots/iae"><%= I18n.t('application.footer.projects.iae') %></a></li>
          </ul>
        </div>
        <div class="col-6 col-lg-2 mb-3">
          <h5><%= I18n.t('application.footer.community.community') %></h5>
          <ul class="list-unstyled">
            <li class="mb-2">
              <a href="https://github.com/orgs/iaebots/projects"><%= I18n.t('application.footer.community.issues') %></a>
            </li>
            <li class="mb-2">
              <a href="https://twitter.com/IaeBots"><%= I18n.t('application.footer.community.twitter') %></a></li>
            <li class="mb-2">
              <a href="https://stackoverflow.com/questions/tagged/iae"><%= I18n.t('application.footer.community.stack-overflow') %></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
</body>
</html>